# Workspace
[workspace]
resolver = "2"

[workspace.package]
version = "0.1.0-dev"
edition = "2024"

[workspace.dependencies]

# Root Package
[package]
name = "suon"
version.workspace = true
edition.workspace = true

[dependencies]
