name: Format

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check
