name: Lint

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clippy:
    name: Running clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
