name: Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Running unit test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose