name: Lint

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  toml:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5

      - name: Install taplo
        run: curl -fsSL https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-linux-x86_64.gz | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Run taplo
        id: taplo
        run: taplo fmt --check --diff

      - name: Taplo info
        if: failure()
        run: |
          echo 'To format TOML files, run: `taplo fmt`'
          echo 'To check for formatting differences, run: `taplo fmt --check --diff`'
          echo 'Learn more about Taplo here: https://taplo.tamasfe.dev/'
          echo 'If you use VSCode, install the "Even Better TOML" extension'
          echo 'Find the VSCode extension here: https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml'
