name: Lint

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5

      - name: Check for typos
        uses: crate-ci/typos@v1.38.1

      - name: Typos info
        if: failure()
        run: |
          echo 'To automatically fix typos, run: `typos -w`'
          echo 'To see a diff of typos, run: `typos`'
          echo 'Learn more about Typos here: https://crates.io/crates/typos'
          echo 'If you use VSCode, you can also install the "Typos Spell Checker" extension'
          echo 'Find the VSCode extension here: https://marketplace.visualstudio.com/items?itemName=tekumara.typos-vscode'


